version: "3"
services:
  app:
    container_name: "app"
    depends_on:
      - "mongo"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - "NODE_ENV=production"
  mongo:
    container_name: "mongo"
    image: "mongo"
    ports:
      - "27017:27017"
